version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:

  openvpn:
    container_name: openvpn
    build: ./openvpn-docker
    ports:
      - 1194:1194/udp
    environment:
      REQ_COUNTRY: US
      REQ_PROVINCE: California
      REQ_CITY: San Francisco
      REQ_ORG: Copyleft Certificate Co
      REQ_OU: My Organizational Unit
      REQ_CN: MyOpenVPN
    volumes:
      - ./openvpn/pki:/etc/openvpn/pki
      - ./openvpn/clients:/opt/app/clients
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - "openvpn"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns: 127.0.0.1
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: 'password'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # Volumes store your data between container upgrades
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
