services:
  openvpn:
    container_name: openvpn
    build: ./openvpn-docker
    ports:
      - "1194:1194/udp"
    networks:
      vpn-net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./openvpn/pki:/etc/openvpn/pki
      - ./openvpn/clients:/etc/openvpn/clients
      - ./openvpn/config:/etc/openvpn/config
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - /dev/net/tun

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - "openvpn"
    networks:
      vpn-net:
        ipv4_address: 172.20.0.2
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "password"
      DNS1: 1.1.1.1 # Cloudflare
      DNS2: 8.8.8.8 # Google
      ServerIP: 172.20.0.2
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  vpn-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

